### ISSUE TITLE
Can you include mlkit to detect face then do mask detection. results would be more accurate right ?

### ISSUE THREAD

**Issue by ganeshchenniah** [AniketSindhu/mask_detector#2]
reference in java code .
https://medium.com/@estebanuri/real-time-face-mask-recognition-in-android-with-tensorflow-lite-215df6327265

**Comment by AniketSindhu** [comment]
of course, it will increase the accuracy of the model but I have no plans to work more in this project

**Comment by ganeshchenniah** [comment]
Thank You . :)
